### ISSUE TITLE
Question: Add butane to install-oc-tools?

### ISSUE THREAD

**Issue by patrickbrooks** [cptmorgan-rh/install-oc-tools#11]
Greetings install-oc-tools!

Apparently a new command line tool called 'butane' is used with OpenShift 4.8:

https://docs.openshift.com/container-platform/4.8/installing/install_config/installing-customizing.html#installation-special-config-butane_installing-customizing

Would it be a good fit to add butane to install-oc-tools.sh?

I can make a first attempt at a pull request, but I'll need a thorough code review ... I don't write sh code very often.

Let me know ... thanks!

**Comment by cptmorgan-rh** [comment]
Hi @patrickbrooks. Thank you for opening the issue. I am in the process of adding the ability to install helm, odo, opm, butane, etc. in the script. Look for it in the next week or two.

**Comment by cptmorgan-rh** [comment]
@patrickbrooks I have just pushed e9e425b to the new_features branch. Please test and let me know if you have any issues.
